import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google";


{/* components */}
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});


const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: "--font-jetbrainsMono",
})



export const metadata = {
  title: "Shree — Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrains.variable}>

        <Header/>
        <StairTransition/>

        <PageTransition>{children}</PageTransition>
        
          

        
        
      </body>
    </html>
  )
}


